### PR TITLE
Frontend/styling, Connecting FE to BE for signup route

### PR DESCRIPTION
**Pull request by PLCoster**
Users can now sign up for an account, this logs them in and redirects to the main page.

Bootstrap styles added to navbar and main page.

### CODE REVIEW

**Review by dreille — APPROVED** [review]
wowee

**Review by errc-lee — APPROVED** [review]
same

**Review by hultzentre — APPROVED** [review]
noice

**Review by labaird — APPROVED** [review]
Looks good. Note: What does devServer historyApiFallback do?

**Pull request merged**
